spring:
  application:
    name: l9g-federated-oidc-redirect-service
  profiles:
    active: default
  config:
    import: optional:file:config.yaml
  messages:
    basename: messages
    encoding: UTF-8

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger:%line - %yellow(%msg %n)"
  level:
    root: OFF
    l9g: OFF

server:
  port: 8081
  servlet:
    context-path: /
    session:
      timeout: 9h

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
